### PR TITLE
Logging

### LINKED ISSUE #10: Improve logging
Currently logging to console is hardcoded:
```
                runCatching {
                    val mappedEntity = deserialize<T>(message.body)

                    rabbitDeliverCallback.invoke(consumerTag, mappedEntity)
                }.getOrElse {
                    it.printStackTrace()
                }
```

It should be possible to plug whatever logger is used in the system instead.

### PR DESCRIPTION
**Pull request by JUtupe**
closes #10

### CODE REVIEW

File: src/test/kotlin/pl/jutupe/ktor_rabbitmq/ConsumerTest.kt [hunk 1]
```diff
@@ -49,4 +52,35 @@ class TestConsumerTest : IntegrationTest() {
             verify { consumer.invoke(any(), eq(body)) }
         }
     }
+
+    @Test
+    fun `should log error when invalid body published`() {
```
Comment (kibertoad) [inline src/test/kotlin/pl/jutupe/ktor_rabbitmq/ConsumerTest.kt:57]: would be also nice to have one for cancellation

**Review by kibertoad — APPROVED** [review]
